<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt" xml:lang="pt"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.340">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Associação Brasileira de Jurimetria">

<title>Processos relacionados à Arbitragem</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="relatorio_files/libs/clipboard/clipboard.min.js"></script>
<script src="relatorio_files/libs/quarto-html/quarto.js"></script>
<script src="relatorio_files/libs/quarto-html/popper.min.js"></script>
<script src="relatorio_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="relatorio_files/libs/quarto-html/anchor.min.js"></script>
<link href="relatorio_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="relatorio_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="relatorio_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="relatorio_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="relatorio_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Índice</h2>
   
  <ul>
  <li><a href="#introdução" id="toc-introdução" class="nav-link active" data-scroll-target="#introdução">Introdução</a></li>
  <li><a href="#download" id="toc-download" class="nav-link" data-scroll-target="#download">Download</a></li>
  <li><a href="#arrumação" id="toc-arrumação" class="nav-link" data-scroll-target="#arrumação">Arrumação</a>
  <ul class="collapse">
  <li><a href="#revisão-manual" id="toc-revisão-manual" class="nav-link" data-scroll-target="#revisão-manual">Revisão manual</a></li>
  <li><a href="#segunda-instância" id="toc-segunda-instância" class="nav-link" data-scroll-target="#segunda-instância">Segunda instância</a></li>
  </ul></li>
  <li><a href="#análise" id="toc-análise" class="nav-link" data-scroll-target="#análise">Análise</a>
  <ul class="collapse">
  <li><a href="#questões-adicionais" id="toc-questões-adicionais" class="nav-link" data-scroll-target="#questões-adicionais">Questões adicionais</a>
  <ul class="collapse">
  <li><a href="#qual-a-proporção-de-resultado-para-a-categoria-anulação-envolvendo-ou-não-a-unimed" id="toc-qual-a-proporção-de-resultado-para-a-categoria-anulação-envolvendo-ou-não-a-unimed" class="nav-link" data-scroll-target="#qual-a-proporção-de-resultado-para-a-categoria-anulação-envolvendo-ou-não-a-unimed">Qual a proporção de resultado para a categoria anulação envolvendo ou não a Unimed?</a></li>
  <li><a href="#qual-o-percentual-de-liminares-deferidas-na-categoria-de-ação-cautelar" id="toc-qual-o-percentual-de-liminares-deferidas-na-categoria-de-ação-cautelar" class="nav-link" data-scroll-target="#qual-o-percentual-de-liminares-deferidas-na-categoria-de-ação-cautelar">Qual o percentual de liminares deferidas na categoria de ação cautelar?</a></li>
  <li><a href="#qual-a-média-e-mediana-de-valor-para-cada-categoria-de-ação" id="toc-qual-a-média-e-mediana-de-valor-para-cada-categoria-de-ação" class="nav-link" data-scroll-target="#qual-a-média-e-mediana-de-valor-para-cada-categoria-de-ação">Qual a média e mediana de valor para cada categoria de ação?</a></li>
  <li><a href="#qual-é-a-taxa-de-favorabilidade-em-anulatórias-ao-longo-do-tempo" id="toc-qual-é-a-taxa-de-favorabilidade-em-anulatórias-ao-longo-do-tempo" class="nav-link" data-scroll-target="#qual-é-a-taxa-de-favorabilidade-em-anulatórias-ao-longo-do-tempo">Qual é a taxa de favorabilidade em anulatórias ao longo do tempo?</a></li>
  <li><a href="#segunda-instância-1" id="toc-segunda-instância-1" class="nav-link" data-scroll-target="#segunda-instância-1">Segunda instância</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#referências" id="toc-referências" class="nav-link" data-scroll-target="#referências">Referências</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Outros formatos</h2><ul><li><a href="relatorio.docx"><i class="bi bi-file-word"></i>MS Word</a></li></ul></div></nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Processos relacionados à Arbitragem</h1>
<p class="subtitle lead">Um levantamento preliminar no banco de sentenças do TJSP</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autor</div>
    <div class="quarto-title-meta-contents">
             <p>Associação Brasileira de Jurimetria </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Data de Publicação</div>
    <div class="quarto-title-meta-contents">
      <p class="date">2 de dezembro de 2022</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="introdução" class="level1">
<h1>Introdução</h1>
<p>O Observatório da Arbitragem é um projeto que visa compreender o reflexo do fenômeno jurídico da arbitragem nos tribunais. Em sua primeira fase, o projeto busca compreender o fluxo dos processos de i) anulação de decisão arbitral, ii) cumprimento de sentença / execução, iii) medida cautelar antecedente ao tribunal arbitral, iv) existência, validade e eficácia da convenção de arbitragem e v) ação para instituição da arbitragem com base no art, 7º da Lei de Arbitragem.</p>
<p>O objetivo do levantamento é realizar uma análise preliminar a partir do banco de sentenças do Tribunal de Justiça de São Paulo (TJSP). O levantamento terá como resultado algumas estatísticas básicas como volume de sentenças ao longo do tempo, proporção de decisões favoráveis ao autor e tempo mediano dos processos. O estudo pode ser utilizado como insumo para decidir sobre a viabilidade de uma pesquisa mais aprofundada – envolvendo análise de autos processuais – a partir dos dados disponibilizados no banco de sentenças.</p>
<p>O presente levantamento descreve o fluxo de download, arrumação e análise dos dados de sentenças relacionadas à arbitragem. Na parte de download, descrevemos os termos utilizados para consulta e o procedimento de acesso aos dados, que são públicos, mas não são abertos. A parte de arrumação descreve todos os passos para chegar da base bruta até a base organizada, informando as colunas utilizadas. A análise mostra os resultados do levantamento, com estatísticas sobre o perfil dos processos, o volume de sentenças ao longo do tempo, a proporção de decisões favoráveis e o tempo médio das ações.</p>
</section>
<section id="download" class="level1">
<h1>Download</h1>
<p>Os dados de processos do TJSP são públicos, mas não são abertos. Isso significa que não existe um meio fácil de obter uma lista de todos os processos que existem no tribunal a partir de um critério jurídico, geográfico ou temporal.</p>
<p>O tribunal, no entanto, disponibiliza ferramentas de consulta. Na <a href="https://esaj.tjsp.jus.br/cjpg/pesquisar.do">Consulta de Julgados do Primeiro Grau (CJPG)</a> é possível acessar, manualmente, a lista de processos a partir de termos de busca (como palavras-chave, classes e assuntos). Cada processo, por sua vez, pode ser pesquisado manualmente em uma consulta de processos <a href="https://esaj.tjsp.jus.br/cpopg/open.do">Consulta de Processos do Primeiro Grau</a>.</p>
<p>Por conta da necessidade de realizar pesquisas no Direito, a ABJ desenvolveu, ao longo de sua história, algumas ferramentas que automatizam o fluxo manual de obtenção de dados. Essas ferramentas utilizam técnicas de raspagem de dados <span class="citation" data-cites="zhaoWebScraping2017">(<a href="#ref-zhaoWebScraping2017" role="doc-biblioref">Zhao 2017</a>)</span> que, em poucas palavras, envolvem imitar o que um ser humano faria para acessar as páginas, mas de forma automática. Vale ressaltar que essa não é uma estratégia oficial nem desejável de ser utilizada ao acessar dados públicos. No entanto, por conta das limitações do tribunal, utilizar raspagem de dados acaba sendo necessário para tornar as pesquisas viáveis.</p>
<p>Ao acessar os dados via raspagem do CJPG, a primeira limitação que aparece são os campos disponíveis. Processos de arbitragem podem aparecer com classes e assuntos processuais<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> que não identificam corretamente os casos. Por exemplo, é comum encontrar como classe “procedimento ordinário” ou como assunto “anulação”. Por isso, a única forma de listar os processos relacionados à arbitragem é através das palavras-chave.</p>
<p>A desvantagem em utilizar palavras-chave é que as pesquisas se limitam ao que as ferramentas de pesquisa disponibilizam. Se a ferramenta de busca é falha, o resultado é falho. De qualquer forma, por falta de outros meios, essa foi a decisão tomada para acessar os processos relacionados à arbitragem.</p>
<p>O termo de busca utilizado para realizar a pesquisa foi <code>"arbitral" OU "lei de arbitragem" OU "9307" OU "9.307"</code>. A ideia da pesquisa foi realizar a busca mais genérica possível relacionada à arbitragem, sem incluir o termo “arbitragem”, já que este aparece no nome das varas, o que implicaria em uma lista com todos os processos da vara.</p>
<p>Outro filtro realizado foi o das varas. Foram consideradas 4 varas no total: 1ª vara empresarial e conflitos de arbitragem, 2ª vara empresarial e conflitos de arbitragem, 1ª vara regional de competência empresarial e de conflitos relacionados à arbitragem e 2ª vara regional de competência empresarial e de conflitos relacionados à arbitragem.</p>
<p>A pesquisa retornou um total de 348 decisões, disponibilizadas entre março de 2018 e novembro de 2022. Dentre esses casos, foram encontrados 338 números de processos únicos, já que um processo pode apresentar mais de uma decisão. A consulta desses processos individualmente retornou 337 casos (1 caso foi descartado por estar em segredo de justiça). A base bruta final, portanto, possui 337 processos.</p>
<p>Neste ponto, uma discussão pode ser iniciada sobre o volume total de ações. Por envolver casos que potencialmente correm em segredo de justiça, é possível que uma parte dos casos não são acessíveis através do banco de sentenças. Além disso, por envolver apenas as varas empresariais, o recorte pode apresentar limitações de espaço (regiões) e tempo (criação das varas)<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>. Por último, por se tratar de um estudo retrospectivo (envolve apenas casos com sentença), pode ser que casos que ainda estão ativos fiquem de fora da lista. De qualquer forma, espera-se que a lista obtida, depois de limpa, possa ser utilizada como amostra aleatória da população de todos os processos relacionados a arbitragem.</p>
</section>
<section id="arrumação" class="level1">
<h1>Arrumação</h1>
<p>O primeiro passo da arrumação dos dados foi a classificação das categorias de processos e remoção de casos que não fazem parte do escopo. Para classificar as cinco categorias, foram utilizados os termos e expressões regulares da <a href="#tbl-rx-tipo">Tabela&nbsp;1</a>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-rx-tipo" class="anchored">
<table class="table table-sm table-striped small">
<caption>Tabela&nbsp;1: Expressões regulares utilizadas para classificar a categoria de ação</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Categoria</th>
<th style="text-align: left;">Expressões regulares</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Instauracao</td>
<td style="text-align: left;">(instauracao)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cumprimento</td>
<td style="text-align: left;">(cumprimento)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Compromisso</td>
<td style="text-align: left;">(compromisso arbitral)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cautelar</td>
<td style="text-align: left;">(cautelar OU antecipada)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Anulacao</td>
<td style="text-align: left;">(anulacao OU nulidade)</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>A <a href="#tbl-tabela-tipo">Tabela&nbsp;2</a> mostra a quantidade de processos detectada em cada categoria. É importante destacar que toda classificação automática pode incorrer em erros, ou seja, pode ser que as categorias finais fiquem incorretas. Os casos vazios foram retirados.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-tabela-tipo" class="anchored">
<table class="table table-sm table-striped small">
<caption>Tabela&nbsp;2: Processos classificados por categoria</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Resultado</th>
<th style="text-align: right;">N</th>
<th style="text-align: right;">%</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Compromisso</td>
<td style="text-align: right;">135</td>
<td style="text-align: right;">39.94%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cumprimento</td>
<td style="text-align: right;">83</td>
<td style="text-align: right;">24.56%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Instauracao</td>
<td style="text-align: right;">44</td>
<td style="text-align: right;">13.02%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cautelar</td>
<td style="text-align: right;">35</td>
<td style="text-align: right;">10.36%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Anulacao</td>
<td style="text-align: right;">34</td>
<td style="text-align: right;">10.06%</td>
</tr>
<tr class="even">
<td style="text-align: left;">(Vazio)</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">2.07%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Total</td>
<td style="text-align: right;">338</td>
<td style="text-align: right;">100.00%</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>O passo seguinte foi a obtenção dos resultados dos processos. Para classificar as categorias de resultados, foram utilizados os termos e expressões regulares da <a href="#tbl-rx-resultado">Tabela&nbsp;3</a>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-rx-resultado" class="anchored">
<table class="table table-sm table-striped small">
<caption>Tabela&nbsp;3: Expressões regulares utilizadas para classificar o resultado</caption>
<colgroup>
<col style="width: 13%">
<col style="width: 87%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Categoria</th>
<th style="text-align: left;">Expressões regulares</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Acordo</td>
<td style="text-align: left;">(homologo o acordo)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Extinto</td>
<td style="text-align: left;">(julgo extinto OU julgo extinta OU determino a extincao OU determinar a extincao)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Improcedente</td>
<td style="text-align: left;">(julgo improcedente OU indefiro a tutela)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Parcial</td>
<td style="text-align: left;">(julgo procedente em parte OU parcialmente procedente OU defiro parcialmente a tutela)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Procedente</td>
<td style="text-align: left;">(julgo (o pedido )?procedente OU homologo OU defiro a tutela)</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>A <a href="#tbl-tabela-resultado">Tabela&nbsp;4</a> mostra a quantidade de processos detectada em cada categoria de resultado. Novamente, a classificação automática pode incorrer em erros, ou seja, pode ser que os resultados estejam incorretos. Os casos vazios foram retirados da análise.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-tabela-resultado" class="anchored">
<table class="table table-sm table-striped small">
<caption>Tabela&nbsp;4: Processos classificados por resultado</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Resultado</th>
<th style="text-align: right;">N</th>
<th style="text-align: right;">%</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Extinto</td>
<td style="text-align: right;">142</td>
<td style="text-align: right;">42.0%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Procedente</td>
<td style="text-align: right;">74</td>
<td style="text-align: right;">21.9%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Improcedente</td>
<td style="text-align: right;">70</td>
<td style="text-align: right;">20.7%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Parcial</td>
<td style="text-align: right;">27</td>
<td style="text-align: right;">8.0%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Acordo</td>
<td style="text-align: right;">21</td>
<td style="text-align: right;">6.2%</td>
</tr>
<tr class="even">
<td style="text-align: left;">(Vazio)</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">1.2%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Total</td>
<td style="text-align: right;">338</td>
<td style="text-align: right;">100.0%</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Por último, as colunas importantes de análise foram construídas. As colunas escolhidas foram: status (em andamento, extinto, em grau de recurso ou suspenso), classe, assunto, valor da causa, processo digital, data de disponibilização da sentença, vara, resultado e tempo (calculado pelo tempo entre a data de distribuição e data da disponibilização da decisão).</p>
<section id="revisão-manual" class="level2">
<h2 class="anchored" data-anchor-id="revisão-manual">Revisão manual</h2>
<p>A base de dados arrumada foi revisada manualmente a partir da leitura dos textos das decisões e outras características dos processos. A revisão foi realizada por profissionais do direito especializados no tema de arbitragem.</p>
<p>A primeira mudança significativa foi com relação aos casos que fazem parte do escopo. Dos 338 casos iniciais, sobraram 289 que faziam parte do escopo<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a>.</p>
<p>Com relação às colunas da base, as principais informações alteradas foram as de categoria e resultado. A informação de categoria foi a que mais sofreu alterações, especialmente em ações de anulação de decisão arbitral, que ficaram maiores. A <a href="#tbl-tabela-tipo-revisao">Tabela&nbsp;5</a> mostra as classificações depois da correção manual.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-tabela-tipo-revisao" class="anchored">
<table class="table table-sm table-striped small">
<caption>Tabela&nbsp;5: Processos classificados por categoria, após revisão</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Resultado</th>
<th style="text-align: right;">N</th>
<th style="text-align: right;">%</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Anulacao</td>
<td style="text-align: right;">95</td>
<td style="text-align: right;">32.87%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cumprimento</td>
<td style="text-align: right;">75</td>
<td style="text-align: right;">25.95%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cautelar</td>
<td style="text-align: right;">63</td>
<td style="text-align: right;">21.80%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Compromisso</td>
<td style="text-align: right;">46</td>
<td style="text-align: right;">15.92%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Instauracao</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">3.46%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Total</td>
<td style="text-align: right;">289</td>
<td style="text-align: right;">100.00%</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Com relação aos resultados, não houve mudanças significativas. A categoria que mais mudou foi a de acordos, que costumam ser difíceis de mapear apenas por palavras-chave. A <a href="#tbl-tabela-resultado-revisao">Tabela&nbsp;6</a> mostra as classificações depois da correção manual. Os resultados completos são apresentados na próxima seção.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-tabela-resultado-revisao" class="anchored">
<table class="table table-sm table-striped small">
<caption>Tabela&nbsp;6: Processos classificados por resultado, após revisão</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Resultado</th>
<th style="text-align: right;">N</th>
<th style="text-align: right;">%</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Extinto</td>
<td style="text-align: right;">124</td>
<td style="text-align: right;">42.9%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Improcedente</td>
<td style="text-align: right;">57</td>
<td style="text-align: right;">19.7%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Acordo</td>
<td style="text-align: right;">43</td>
<td style="text-align: right;">14.9%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Procedente</td>
<td style="text-align: right;">43</td>
<td style="text-align: right;">14.9%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Parcial</td>
<td style="text-align: right;">22</td>
<td style="text-align: right;">7.6%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Total</td>
<td style="text-align: right;">289</td>
<td style="text-align: right;">100.0%</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Por último, duas colunas foram adicionadas após a classificação manual. A primeira é com relação à concessão de liminar em casos de medida cautelar. A segunda é que, na revisão manual, vários casos relacionados à Unimed foram detectados. Uma coluna <code>unimed</code> foi adicionada para permitir novos filtros de análise.</p>
<p>No final, a base ficou com 289 linhas e 13 colunas, contendo todas as informações utilizadas na parte de análise. A base de dados em Excel pode ser baixada <a href="https://github.com/abjur/obsArb/raw/main/inst/da_arbitragem.xlsx">neste link</a>.</p>
</section>
<section id="segunda-instância" class="level2">
<h2 class="anchored" data-anchor-id="segunda-instância">Segunda instância</h2>
<p>Depois de baixar e revisar as sentenças, procurou-se os números de processos obtidos na segunda instância. Foram considerados apenas casos com apenas um recurso (agravo de instrumento ou apelação). Por exemplo, processos que tiveram mais de um agravo de instrumento foram desconsiderados.</p>
<p>Dos 289 processos, 173 apresentaram algum recurso, sendo 126 (73%) com classe “Apelação Cível” e 47 (27%) com classe “Agravo de Instrumento”. Nessa base, somente 132 (76%) possuem alguma decisão, sendo 98 apelações e 34 agravos. Os demais recursos não apresentavam uma tabela de decisões na consulta processual. Além da informação da decisão, também foi coletada a informação do status dos processos no momento da coleta. Essa informação foi extraída diretamente da consulta processual do TJSP, sem nenhum tratamento posterior.</p>
<p>Após o filtro inicial, a base passou por uma revisão manual. A revisão foi realizada nos 57 casos que tinham alguma decisão diferente de improcedente. Na nova análise, foram incluídas duas informações manualmente: se a decisão arbitral foi reformada e uma coluna identificando se o caso era relacionado com a Unimed.</p>
<p>A base de segunda instância foi considerada para calcular a taxa de recorribilidade e a taxa de decisões favoráveis na segunda instância. A taxa de reforma da decisão arbitral foi calculada a partir da análise manual.</p>
<p>A base considerada possui 173 linhas e 8 colunas. A base de dados em Excel pode ser baixada <a href="https://github.com/abjur/obsArb/raw/main/inst/da_cposg_tidy.xlsx">neste link</a>.</p>
</section>
</section>
<section id="análise" class="level1">
<h1>Análise</h1>
<p>A base possui 289 casos, dentre os quais 226 são digitais ou digitalizados (78%). Em uma nova análise manual mais aprofundada, seriam considerados apenas processos digitais ou digitalizados.</p>
<p>A <a href="#tbl-status">Tabela&nbsp;7</a> mostra os status dos processos no momento da coleta dos dados, em novembro/2022. A maioria dos casos está extinta e aproximadamente um quinto dos casos está em grau de recurso.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-status" class="anchored">
<table class="table table-sm table-striped small">
<caption>Tabela&nbsp;7: Status dos processos no momento da coleta dos dados</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Status</th>
<th style="text-align: right;">N</th>
<th style="text-align: right;">%</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Extinto</td>
<td style="text-align: right;">171</td>
<td style="text-align: right;">59.2%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Em grau de recurso</td>
<td style="text-align: right;">62</td>
<td style="text-align: right;">21.5%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">(Vazio)</td>
<td style="text-align: right;">50</td>
<td style="text-align: right;">17.3%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Suspenso</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">2.1%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Total</td>
<td style="text-align: right;">289</td>
<td style="text-align: right;">100.0%</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Em seguida, são apresentadas tabelas das classes e assuntos mais comuns nos processos encontrados. É importante destacar que classes e assuntos nem sempre identificam corretamente o tipo de ação, tanto por motivos de taxonomia (o tipo de processo não existe na classificação do CNJ) quanto por motivos de má classificação (a pessoa que protocolou a ação colocou uma classe/assunto inadequada). Por isso, a classe e assunto não está sendo usada para classificar os tipos de processo.</p>
<p>A <a href="#tbl-classe">Tabela&nbsp;8</a> mostra as classes processuais mais comuns encontradas. É possível notar que existem muitas classes que não são relacionadas diretamente a arbitragem.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-classe" class="anchored">
<table class="table table-sm table-striped small">
<caption>Tabela&nbsp;8: Classes mais comuns</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Classe</th>
<th style="text-align: right;">N</th>
<th style="text-align: right;">%</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Compromisso Arbitral</td>
<td style="text-align: right;">77</td>
<td style="text-align: right;">26.6%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Procedimento Comum Cível</td>
<td style="text-align: right;">64</td>
<td style="text-align: right;">22.1%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cumprimento de sentença - Lei Arbitral (Lei 9.307/1996)</td>
<td style="text-align: right;">54</td>
<td style="text-align: right;">18.7%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Tutela Cautelar Antecedente</td>
<td style="text-align: right;">42</td>
<td style="text-align: right;">14.5%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cumprimento de sentença</td>
<td style="text-align: right;">22</td>
<td style="text-align: right;">7.6%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Tutela Antecipada Antecedente</td>
<td style="text-align: right;">16</td>
<td style="text-align: right;">5.5%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Produção Antecipada da Prova</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">2.4%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Dissolução Parcial de Sociedade</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">1.4%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Embargos à Execução</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.7%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Interpelação</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.3%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Total</td>
<td style="text-align: right;">289</td>
<td style="text-align: right;">100.0%</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>A <a href="#tbl-assunto">Tabela&nbsp;9</a> mostra os dez assuntos processuais mais comuns encontrados. Assim como nas classes, é possível notar que existem muitos assuntos que não são relacionadas diretamente a arbitragem.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-assunto" class="anchored">
<table class="table table-sm table-striped small">
<caption>Tabela&nbsp;9: Assuntos mais comuns</caption>
<colgroup>
<col style="width: 86%">
<col style="width: 4%">
<col style="width: 8%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Assunto</th>
<th style="text-align: right;">N</th>
<th style="text-align: right;">%</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Defeito, nulidade ou anulação</td>
<td style="text-align: right;">92</td>
<td style="text-align: right;">31.8%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sentença arbitral (artigo 515, inciso VII, CPC)</td>
<td style="text-align: right;">60</td>
<td style="text-align: right;">20.8%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Liminar</td>
<td style="text-align: right;">45</td>
<td style="text-align: right;">15.6%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Outros</td>
<td style="text-align: right;">42</td>
<td style="text-align: right;">14.5%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Franquia</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">4.5%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Medida cautelar ou de urgência pré-arbitral (Art. 22-A, Lei nº 9.307/96)</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">4.5%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Constrição / Penhora / Avaliação / Indisponibilidade de Bens</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">2.1%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Obrigação de Fazer / Não Fazer</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">1.7%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Valor da Execução / Cálculo / Atualização</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">1.7%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Obrigações</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">1.4%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Provas em geral</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">1.4%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Total</td>
<td style="text-align: right;">289</td>
<td style="text-align: right;">100.0%</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>A <a href="#tbl-valor">Tabela&nbsp;10</a> mostra a contagem de processos por faixa de valores de causa. É possível notar que existe uma alta assimetria, já que temos vários processos de até 10 mil reais, mas também processos de mais de 10 milhões de reais.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-valor" class="anchored">
<table class="table table-sm table-striped small">
<caption>Tabela&nbsp;10: Faixas de valores</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Faixa</th>
<th style="text-align: right;">N</th>
<th style="text-align: right;">%</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Até R$ 10.000</td>
<td style="text-align: right;">102</td>
<td style="text-align: right;">35.3%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Entre R$ 10.000 e R$ 100.000</td>
<td style="text-align: right;">63</td>
<td style="text-align: right;">21.8%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Entre R$ 100.000 e R$ 1 milhão</td>
<td style="text-align: right;">74</td>
<td style="text-align: right;">25.6%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Entre R$ 1 milhão e R$ 10 milhões</td>
<td style="text-align: right;">28</td>
<td style="text-align: right;">9.7%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">R$ 10 milhões ou mais</td>
<td style="text-align: right;">21</td>
<td style="text-align: right;">7.3%</td>
</tr>
<tr class="even">
<td style="text-align: left;">(Vazio)</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.3%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Total</td>
<td style="text-align: right;">289</td>
<td style="text-align: right;">100.0%</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>A <a href="#tbl-vara">Tabela&nbsp;11</a> mostra a contagem de processos por vara. As varas empresariais do foro central cível concentram a maior parte dos casos. Por conta do pequeno número de informações, as análises de contagem de resultados e categorias por vara vão desconsiderar as RAJs.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-vara" class="anchored">
<table class="table table-sm table-striped small">
<caption>Tabela&nbsp;11: Quantidade de processos por vara</caption>
<colgroup>
<col style="width: 88%">
<col style="width: 4%">
<col style="width: 7%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Faixa</th>
<th style="text-align: right;">N</th>
<th style="text-align: right;">%</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1ª VARA EMPRESARIAL E CONFLITOS DE ARBITRAGEM</td>
<td style="text-align: right;">140</td>
<td style="text-align: right;">48.4%</td>
</tr>
<tr class="even">
<td style="text-align: left;">2ª VARA EMPRESARIAL E CONFLITOS DE ARBITRAGEM</td>
<td style="text-align: right;">137</td>
<td style="text-align: right;">47.4%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1ª Vara Regional de Competência Empresarial e de Conflitos Relacionados à Arbitragem</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">2.1%</td>
</tr>
<tr class="even">
<td style="text-align: left;">2ª Vara Regional de Competência Empresarial e de Conflitos Relacionados à Arbitragem</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">2.1%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Total</td>
<td style="text-align: right;">289</td>
<td style="text-align: right;">100.0%</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>A <a href="#fig-no-tempo">Figura&nbsp;1</a> mostra o volume de decisões ao longo do tempo, considerando como base a data de disponibilização das sentenças. É possível notar um aumento na quantidade de decisões nos anos de 2021 e 2022 (que ainda não acabou).</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-no-tempo" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="relatorio_files/figure-html/fig-no-tempo-1.png" class="img-fluid figure-img" width="2100"></p>
<figcaption class="figure-caption">Figura&nbsp;1: Quantidade de decisões por ano</figcaption>
</figure>
</div>
</div>
</div>
<p>A <a href="#fig-no-tempo-categoria">Figura&nbsp;2</a> mostra o volume de decisões ao longo do tempo, separando por categoria de caso. Com exceção das ações de Anulação, é possível observar um crescimento de casos nos anos de 2021 e 2022.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-no-tempo-categoria" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="relatorio_files/figure-html/fig-no-tempo-categoria-1.png" class="img-fluid figure-img" width="2100"></p>
<figcaption class="figure-caption">Figura&nbsp;2: Quantidade de decisões por ano e categoria</figcaption>
</figure>
</div>
</div>
</div>
<p>A <a href="#tbl-resultado">Tabela&nbsp;12</a> mostra os resultados dos processos por categoria. Nas últimas linha e coluna, são apresentadas as contagens e proporções marginais. A proporção de casos extintos observada é mais alta do que o comum em análises de processos do TJSP. A taxa de procedência em anulatórias (considerando casos procedentes, parcialmente procedentes e acordos) é de 45%.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-resultado" class="anchored">
<table class="table table-sm table-striped small">
<caption>Tabela&nbsp;12: Resultados dos processos por categoria</caption>
<colgroup>
<col style="width: 16%">
<col style="width: 12%">
<col style="width: 13%">
<col style="width: 17%">
<col style="width: 12%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Categoria</th>
<th style="text-align: left;">Acordo</th>
<th style="text-align: left;">Extinto</th>
<th style="text-align: left;">Improcedente</th>
<th style="text-align: left;">Parcial</th>
<th style="text-align: left;">Procedente</th>
<th style="text-align: left;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Anulacao</td>
<td style="text-align: left;">2 (2%)</td>
<td style="text-align: left;">6 (6%)</td>
<td style="text-align: left;">46 (48%)</td>
<td style="text-align: left;">16 (17%)</td>
<td style="text-align: left;">25 (26%)</td>
<td style="text-align: left;">95 (33%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cautelar</td>
<td style="text-align: left;">9 (14%)</td>
<td style="text-align: left;">40 (63%)</td>
<td style="text-align: left;">10 (16%)</td>
<td style="text-align: left;">0 (0%)</td>
<td style="text-align: left;">4 (6%)</td>
<td style="text-align: left;">63 (22%)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Compromisso</td>
<td style="text-align: left;">0 (0%)</td>
<td style="text-align: left;">34 (74%)</td>
<td style="text-align: left;">1 (2%)</td>
<td style="text-align: left;">5 (11%)</td>
<td style="text-align: left;">6 (13%)</td>
<td style="text-align: left;">46 (16%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cumprimento</td>
<td style="text-align: left;">30 (40%)</td>
<td style="text-align: left;">44 (59%)</td>
<td style="text-align: left;">0 (0%)</td>
<td style="text-align: left;">1 (1%)</td>
<td style="text-align: left;">0 (0%)</td>
<td style="text-align: left;">75 (26%)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Instauracao</td>
<td style="text-align: left;">2 (20%)</td>
<td style="text-align: left;">0 (0%)</td>
<td style="text-align: left;">0 (0%)</td>
<td style="text-align: left;">0 (0%)</td>
<td style="text-align: left;">8 (80%)</td>
<td style="text-align: left;">10 (3%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Total</td>
<td style="text-align: left;">43 (15%)</td>
<td style="text-align: left;">124 (43%)</td>
<td style="text-align: left;">57 (20%)</td>
<td style="text-align: left;">22 (8%)</td>
<td style="text-align: left;">43 (15%)</td>
<td style="text-align: left;">289 (100%)</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>A <a href="#fig-resultado-vara">Figura&nbsp;3</a> mostra os resultados dos processos por categoria e vara, considerando apenas as duas varas empresariais. A quantidade de processos é muito pequena para obter resultados conclusivos, mas aparentemente a segunda vara tende a dar mais resultados procedentes ou parcialmente procedentes nas ações anulatórias.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-resultado-vara" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="relatorio_files/figure-html/fig-resultado-vara-1.png" class="img-fluid figure-img" width="2400"></p>
<figcaption class="figure-caption">Figura&nbsp;3: Proporção dos resultados dos processos por categoria e vara</figcaption>
</figure>
</div>
</div>
</div>
<p>Finalmente, a <a href="#tbl-tempo">Tabela&nbsp;13</a> mostra os tempos médios e medianos, geral e por categoria. Os processos mais longos são os de compromisso arbitral, com mediana de quase um ano. Já os processos mais curtos são os de anulação, com mediana de aproximadamente seis meses.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-tempo" class="anchored">
<table class="table table-sm table-striped small">
<caption>Tabela&nbsp;13: Estatísticas descritivas dos tempos dos processos</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Categoria</th>
<th style="text-align: right;">N</th>
<th style="text-align: right;">Média</th>
<th style="text-align: right;">Mediana</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Compromisso</td>
<td style="text-align: right;">46</td>
<td style="text-align: right;">353.6</td>
<td style="text-align: right;">328.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Instauracao</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">462.7</td>
<td style="text-align: right;">301.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cumprimento</td>
<td style="text-align: right;">75</td>
<td style="text-align: right;">306.5</td>
<td style="text-align: right;">251.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cautelar</td>
<td style="text-align: right;">63</td>
<td style="text-align: right;">232.7</td>
<td style="text-align: right;">194.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Anulacao</td>
<td style="text-align: right;">95</td>
<td style="text-align: right;">274.6</td>
<td style="text-align: right;">188.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Total</td>
<td style="text-align: right;">289</td>
<td style="text-align: right;">292.8</td>
<td style="text-align: right;">227.0</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<section id="questões-adicionais" class="level2">
<h2 class="anchored" data-anchor-id="questões-adicionais">Questões adicionais</h2>
<p>Após a revisão das análises, um novo conjunto de perguntas foi gerado. As perguntas foram respondidas com os gráficos e tabelas que seguem.</p>
<section id="qual-a-proporção-de-resultado-para-a-categoria-anulação-envolvendo-ou-não-a-unimed" class="level3">
<h3 class="anchored" data-anchor-id="qual-a-proporção-de-resultado-para-a-categoria-anulação-envolvendo-ou-não-a-unimed">Qual a proporção de resultado para a categoria anulação envolvendo ou não a Unimed?</h3>
<p>A <a href="#tbl-resultado-unimed">Tabela&nbsp;14</a> mostra as proporções de resultados em processos de anulação considerando ou não a Unimed como parte. A taxa de casos favoráveis (soma de acordos, procedentes e parcialmente procedentes) é significativamente maior em casos envolvendo a Unimed. Para os demais casos, a taxa de casos favoráveis é de apenas 22%.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-resultado-unimed" class="anchored">
<table class="table table-sm table-striped small">
<caption>Tabela&nbsp;14: Resultados dos processos de anulação pela existência ou não da Unimed como parte</caption>
<colgroup>
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 12%">
<col style="width: 20%">
<col style="width: 13%">
<col style="width: 16%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Unimed</th>
<th style="text-align: left;">Acordo</th>
<th style="text-align: left;">Extinto</th>
<th style="text-align: left;">Improcedente</th>
<th style="text-align: left;">Parcial</th>
<th style="text-align: left;">Procedente</th>
<th style="text-align: left;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Não</td>
<td style="text-align: left;">2 (5%)</td>
<td style="text-align: left;">6 (16%)</td>
<td style="text-align: left;">23 (62%)</td>
<td style="text-align: left;">2 (5%)</td>
<td style="text-align: left;">4 (11%)</td>
<td style="text-align: left;">37 (39%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sim</td>
<td style="text-align: left;">0 (0%)</td>
<td style="text-align: left;">0 (0%)</td>
<td style="text-align: left;">23 (40%)</td>
<td style="text-align: left;">14 (24%)</td>
<td style="text-align: left;">21 (36%)</td>
<td style="text-align: left;">58 (61%)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Total</td>
<td style="text-align: left;">2 (2%)</td>
<td style="text-align: left;">6 (6%)</td>
<td style="text-align: left;">46 (48%)</td>
<td style="text-align: left;">16 (17%)</td>
<td style="text-align: left;">25 (26%)</td>
<td style="text-align: left;">95 (100%)</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section>
<section id="qual-o-percentual-de-liminares-deferidas-na-categoria-de-ação-cautelar" class="level3">
<h3 class="anchored" data-anchor-id="qual-o-percentual-de-liminares-deferidas-na-categoria-de-ação-cautelar">Qual o percentual de liminares deferidas na categoria de ação cautelar?</h3>
<p>A base contem 63 ações cautelares, pouco mais de um quinto da base completa. A <a href="#tbl-cautelar-liminar">Tabela&nbsp;15</a> mostra os resultados das liminares nessas ações. É possível identificar que quase metade das liminares não são concedias. Importante destacar que, em 6 casos, a decisão liminar não foi encontrada.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-cautelar-liminar" class="anchored">
<table class="table table-sm table-striped small">
<caption>Tabela&nbsp;15: Resultados das liminares em ações cautelares.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Resultado</th>
<th style="text-align: right;">N</th>
<th style="text-align: right;">%</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Não</td>
<td style="text-align: right;">30</td>
<td style="text-align: right;">47.6%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sim</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">31.7%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Parcial</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">11.1%</td>
</tr>
<tr class="even">
<td style="text-align: left;">(Vazio)</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">9.5%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Total</td>
<td style="text-align: right;">63</td>
<td style="text-align: right;">100.0%</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section>
<section id="qual-a-média-e-mediana-de-valor-para-cada-categoria-de-ação" class="level3">
<h3 class="anchored" data-anchor-id="qual-a-média-e-mediana-de-valor-para-cada-categoria-de-ação">Qual a média e mediana de valor para cada categoria de ação?</h3>
<p>Finalmente, a <a href="#tbl-valor-tipo">Tabela&nbsp;16</a> mostra os valores médios e medianos das causas, geral e por categoria. Os processos de maior valor são as anulatórias, com mediana de R$ 264.802,79. Já os processos de menor valor são as cautelares e instauração, com mediana de dez mil reais, provavelmente colocados apenas como valores de referência.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-valor-tipo" class="anchored">
<table class="table table-sm table-striped small">
<caption>Tabela&nbsp;16: Estatísticas descritivas dos valores de causa dos processos</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Categoria</th>
<th style="text-align: right;">N</th>
<th style="text-align: left;">Média</th>
<th style="text-align: left;">Mediana</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Anulacao</td>
<td style="text-align: right;">95</td>
<td style="text-align: left;">R$ 3.601.345,63</td>
<td style="text-align: left;">R$ 264.802,79</td>
</tr>
<tr class="even">
<td style="text-align: left;">Compromisso</td>
<td style="text-align: right;">46</td>
<td style="text-align: left;">R$ 10.081.664,83</td>
<td style="text-align: left;">R$ 83.815,77</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cumprimento</td>
<td style="text-align: right;">75</td>
<td style="text-align: left;">R$ 1.394.104,16</td>
<td style="text-align: left;">R$ 23.468,15</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cautelar</td>
<td style="text-align: right;">63</td>
<td style="text-align: left;">R$ 3.326.566,44</td>
<td style="text-align: left;">R$ 10.000,00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Instauracao</td>
<td style="text-align: right;">10</td>
<td style="text-align: left;">R$ 25.058,13</td>
<td style="text-align: left;">R$ 10.000,00</td>
</tr>
<tr class="even">
<td style="text-align: left;">Total</td>
<td style="text-align: right;">289</td>
<td style="text-align: left;">R$ 3.884.973,58</td>
<td style="text-align: left;">R$ 80.355,58</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section>
<section id="qual-é-a-taxa-de-favorabilidade-em-anulatórias-ao-longo-do-tempo" class="level3">
<h3 class="anchored" data-anchor-id="qual-é-a-taxa-de-favorabilidade-em-anulatórias-ao-longo-do-tempo">Qual é a taxa de favorabilidade em anulatórias ao longo do tempo?</h3>
<p>A <a href="#fig-anulacao-no-tempo">Figura&nbsp;4</a> mostra a taxa de casos favoráveis (procedentes, parcialmente procedentes e acordos) em ações anulatórias por ano. Apesar da pequena quantidade de dados, é possível observar que a proporção de decisões favoráveis detectada em 2021 e 2022 é menor.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-anulacao-no-tempo" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="relatorio_files/figure-html/fig-anulacao-no-tempo-1.png" class="img-fluid figure-img" width="2100"></p>
<figcaption class="figure-caption">Figura&nbsp;4: Quantidade de decisões por ano</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="segunda-instância-1" class="level3">
<h3 class="anchored" data-anchor-id="segunda-instância-1">Segunda instância</h3>
<p>A Tabela <a href="#tbl-2inst-status">Tabela&nbsp;17</a> mostra os status dos processos de acordo com as categorias fornecidas pelo TJSP no momento de coleta. Quase 41% dos recursos foram encerrados e 26% foram arquivados administrativamente.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-2inst-status" class="anchored">
<table class="table table-sm table-striped small">
<caption>Tabela&nbsp;17: Status dos processos na segunda instância de acordo com as categorias fornecidas pelo TJSP</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Staus</th>
<th style="text-align: right;">N</th>
<th style="text-align: right;">%</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Encerrado</td>
<td style="text-align: right;">70</td>
<td style="text-align: right;">40.5%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Arquivado administrativamente</td>
<td style="text-align: right;">45</td>
<td style="text-align: right;">26.0%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Remetido a Outro Tribunal</td>
<td style="text-align: right;">24</td>
<td style="text-align: right;">13.9%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ativo</td>
<td style="text-align: right;">18</td>
<td style="text-align: right;">10.4%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Julgado</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">8.7%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Processo não distribuído</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.6%</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>A taxa de recorribilidade estimada é de quase 60%. Isso ocorre porque foram encontrados 173 recursos nos 289 casos estudados. Dividindo as taxas por categoria de processo, encontra-se o resultado da <a href="#tbl-tx-recorr-categoria">Tabela&nbsp;18</a>. É possível notar que as anulatórias são as que apresentam maior taxa de recorribilidade.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-tx-recorr-categoria" class="anchored">
<table class="table table-sm table-striped small">
<caption>Tabela&nbsp;18: Quantidade e taxa de recorribilidade por categoria.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Categoria</th>
<th style="text-align: right;">N total</th>
<th style="text-align: right;">N com recursos</th>
<th style="text-align: right;">%</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Anulacao</td>
<td style="text-align: right;">95</td>
<td style="text-align: right;">88</td>
<td style="text-align: right;">92.6%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cautelar</td>
<td style="text-align: right;">63</td>
<td style="text-align: right;">41</td>
<td style="text-align: right;">65.1%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Compromisso</td>
<td style="text-align: right;">46</td>
<td style="text-align: right;">30</td>
<td style="text-align: right;">65.2%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cumprimento</td>
<td style="text-align: right;">75</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">12.0%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Instauracao</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">50.0%</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Já com relação à taxa de recursos providos ou providos em parte, observa-se que, dos 132 casos com alguma decisão, 44 (33%) foram totalmente providos ou providos em parte. Considerando apenas os processos com categoria de anulatória, a taxa de recursos providos ou providos em parte é de 41% (32 de 78 casos).</p>
<p>Com relação à Unimed, observa-se que 56 dos 132 (42%) dos recursos com decisão têm relação com a Unimed. A taxa de recursos providos (parcial ou totalmente) nos casos que envolvem Unimed é de 52% (29 de 56 casos), sendo que 41% (23 de 56) são providos em parte. Já nos casos que não envolvem Unimed, a taxa de recursos providos é de 20% (15 de 76 casos), sendo que 8% (6 de 76) são providos em parte.</p>
<p>Finalmente, com relação à reforma da decisão arbitral nas anulatórias, foi identificada uma proporção de 26% (28 de 108 casos). Isso significa que, dos casos que chegaram à segunda instância e tiveram alguma decisão de mérito (108 dos 132 casos), a decisão final sobre a sentença arbitral foi de reformar da decisão arbitral, pelo menos em parte. Ao retirar as ações relacionadas à Unimed, no entanto, sobram apenas 59 casos, sendo 1 reforma e 58 sem reforma.</p>
</section>
</section>
</section>
<section id="referências" class="level1 unnumbered">
<h1 class="unnumbered">Referências</h1>
<div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-zhaoWebScraping2017" class="csl-entry" role="listitem">
Zhao, Bo. 2017. <span>«Web Scraping»</span>. <em>Encyclopedia of big data</em>, 1–3.
</div>
</div>
</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Notas de rodapé</h2>

<ol>
<li id="fn1"><p>Classes e assuntos são listas de tipos de processos organizadas pelo Conselho Nacional de Justiça (CNJ), através das Tabelas Processuais Unificadas (TPU), Res. 46 CNJ.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>As três primeiras varas empresariais tiveram sua criação autorizada no dia 14 de dezembro por deliberação unânime do Órgão Especial do Tribunal de Justiça do Estado de São Paulo. Link para o parecer em <a href="https://bit.ly/parecer-varas" class="uri">https://bit.ly/parecer-varas</a>. Acesso em 03 de maio de 2023.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>O critério de exclusão dizia respeito à pertinência do caso ao objeto da pesquisa. Assim, casos nos quais as expressões apresentavam significados distintos (falsos cognatos) foram excluídos. Por exemplo, arbitragem no sentido de arbitragem de preço e não como método de resolução de disputas. Um caso foi identificado em uma nova categoria “Carta Arbitral” (1099760-61.2021.8.26.0100). O caso foi desconsiderado da análise.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copiada");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copiada");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>